# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20170512_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_players',
            field=models.IntegerField(default=0),
        ),
    ]
