# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_current_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='current_players',
        ),
    ]
