# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_remove_tournament_current_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
