# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_deck_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deck',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screens'),
        ),
    ]
